description: Layrz API models for Dart/Flutter. This package contains the models used by the Layrz API.
name: layrz_models
version: "3.4.51"
repository: https://github.com/goldenm-software/layrz_models

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.9.0
  web: ^1.1.0
  collection: ^1.18.0
  recase: ^4.1.0
  latlong2: ^0.9.1
  layrz_icons: ^1.0.3
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  layrz_logging: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.2.0
  json_serializable: ^6.9.5
