name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+\+[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-dev[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-alpha[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-beta[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-prerelease[0-9]+'

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/goldenm-software/flutter-web-builder:flutter3.35.7-uv-python3.13
      options: --user root
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get tag version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Test
        run: |
          flutter test

      - name: Authenticate
        env:
          VERSION: ${{ env.VERSION }}
          PUB_JSON: ${{ secrets.LAYRZ_PUB_TOKEN }}
        run: |
          uv run authenticate.py

      - name: Publish
        run: |
          flutter pub publish --force

      - name: Cleanup
        run: |
          dart pub token remove https://pub.dev
