name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+\+[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-dev[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-alpha[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-beta[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-prerelease[0-9]+'

jobs:
  deploy-dart:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Get tag version
        id: get_version
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          CLEAN_VERSION=${TAG_NAME#v}
          echo "VERSION=$CLEAN_VERSION" >> $GITHUB_ENV

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.38.8
          cache: true

      - name: Sed version
        run: |
          sed -i "s/^version: .*/version: $VERSION/" pubspec.yaml

      - name: Install dependencies
        run: flutter pub get

      - name: Run checks
        run: flutter analyze

      - name: Dry run
        run: flutter pub publish --dry-run

      - name: Publish to pub.dev
        run: flutter pub publish --force

      - name: Rename tag when fails
        if: failure()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          TAG_NAME=${GITHUB_REF#refs/tags/}
          NEW_TAG="failed-${TAG_NAME}-${TIMESTAMP}"
          git tag $NEW_TAG
          git push origin $NEW_TAG
          git push --delete origin $TAG_NAME

      - name: Create GitHub Release
        if: success()
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
